#version 460 core
layout(local_size_x = 256) in;
layout(location = 0) uniform uint frame;

layout(std430, binding = 0) buffer counter_buf { uvec3 counter; };
layout(std430, binding = 1) writeonly buffer active_chunks { uint active_subchunks[]; };
layout(std430, binding = 2) readonly buffer updated_chunks { uint subchunks[]; };
const uint x_max = 2048 * 256 / 64;

shared uint buff_needed;
void main(){
    uint interior_x = gl_GlobalInvocationID.x % (x_max - 2) + 1;
    uint interior_y = gl_GlobalInvocationID.x / (x_max - 2) + 1;
    uint subchunk_id = interior_y * x_max + interior_x;

    uint id = 0;
    bool is_active = subchunks[subchunk_id] == frame;
    if(gl_LocalInvocationID.x == 0){
        buff_needed = 0;
    }
    memoryBarrierShared();
    barrier();

    
    if(is_active){
        id = atomicAdd(buff_needed, 1);
    }
    barrier();

    if(gl_LocalInvocationID.x == 0 && buff_needed != 0){
        buff_needed = atomicAdd(counter.x, buff_needed);
    }
    memoryBarrierShared();
    barrier();

    if(is_active){
        active_subchunks[buff_needed + id] = subchunk_id;
    }
}